keys:
 - &admin_homelab age130ky00j8mzpn4p3spcmv7h6xhppjf47hnapwdt8mm0v488xa53vqctmfkg
 - &host_astrocontrol age1elye06xqt69qezg3drhymdu0drcx23hkj9y5gy9656y4nvw4l4eqzg99y4
 - &host_kiroshi age1ffsxuckdem6jtcg7asuwz2qvszzd9vky0echfs22sstzm0nk2phqwt9hzn
 - &host_memory_hole age1d2kx69cg6ayhuvhwlyq682ddaf20zfs6k0thhjeq77rtrw80qs6q7wqe99
creation_rules:
 - path_regex: common/secrets\.yaml
   key_groups:
   - age:
     - *admin_homelab
     - *host_astrocontrol
     - *host_kiroshi
     - *host_memory_hole
 - path_regex: memory-hole/secrets\.yaml
   key_groups:
   - age:
     - *admin_homelab
     - *host_memory_hole
